### PR TITLE
Add simple disk library

### PR DESCRIPTION
**Pull request by iiSaLMaN**
Add a simple disk library: `read_sector` `write_sector` using bios interrupt calls.

### CODE REVIEW

**Comment by mintsuki** [comment]
Use the same coding style as the rest of the project, it's not hard.

**Comment by too-r** [comment]
This is still inconsistent with the coding style in the rest of the project. Braces do not go on a newline in functions or struct definitions.

**Comment by mintsuki** [comment]
What toor said, and also do not pass structs as arguments, use struct pointers. Also do not return structs.
This is also part of our "coding style" (or coding conventions, rather).

**Comment by mintsuki** [comment]
Also, something you should keep in mind. Instead of translating 32 bit pointers to segment:offset, we want to be able to load the sector _wherever_ we want in the 32 bit address space. Therefore what you should do is load the sector at a fixed location in a buffer:
```c
static uint8_t sector_buf[512];
```
And then you memcpy the sector to its final location.
Since we're at an address <64k you can hardcode the segment to 0 in the dap, and point the offset to `sector_buf`.

**Comment by mintsuki** [comment]
One last note, this:
```c
static struct dap
{
    unsigned short size;
    unsigned short count;
    unsigned short offset;
    unsigned short segment;
    unsigned long long lba;
};

static struct dap dap = { DAP_SIZE, 0, 0, 0, 0 };
```
can be written as
```c
static struct {
    unsigned short size;
    unsigned short count;
    unsigned short offset;
    unsigned short segment;
    unsigned long long lba;
} dap = { DAP_SIZE, 0, 0, 0, 0 };
```
And it will look prettier :)

**Comment by iiSaLMaN** [comment]
> This is still inconsistent with the coding style in the rest of the project. Braces do not go on a newline in functions or struct definitions.

Woah, i didn't notice that lol

**Pull request merged**
